In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
from datetime import datetime
import re
from unidecode import unidecode

tqdm.pandas()

In [2]:
page = requests.get(
    "https://thefangirlverdict.com/index/all-reviews/full-list-of-shows/"
)
soup = BeautifulSoup(page.content)

In [3]:
for p in soup.find_all("p", style="text-align:justify"):
    p.decompose()

In [4]:
names = []
urls = []
grades = []

for x in tqdm(range(1200)):

    element = soup.select_one("#post-7658 > div > p:nth-child(" + str(x) + ")")
    if element is None:
        continue

    kdrama = element.findChildren("a", recursive=False)
    # print(kdrama)
    grade = element.findChildren("strong", recursive=False)
    # print(grade)

    if kdrama:
        names.append(kdrama[0].contents[0])
        urls.append(kdrama[0].get("href"))
        if grade:
            grades.append(grade[0].text)
        else:
            grades.append("NA")

  0%|          | 0/1200 [00:00<?, ?it/s]/var/folders/cf/kl9c18yn5d34tvgvld3436y40000gn/T/ipykernel_48995/3493090341.py:11: DeprecationWarning: Call to deprecated method findChildren. (Replaced by find_all) -- Deprecated since version 3.0.0.
  kdrama = element.findChildren("a", recursive=False)
/var/folders/cf/kl9c18yn5d34tvgvld3436y40000gn/T/ipykernel_48995/3493090341.py:13: DeprecationWarning: Call to deprecated method findChildren. (Replaced by find_all) -- Deprecated since version 3.0.0.
  grade = element.findChildren("strong", recursive=False)
100%|██████████| 1200/1200 [20:33<00:00,  1.03s/it]

In [5]:
df = pd.DataFrame({"source": names, "url": urls, "rating": grades})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 863 entries, 0 to 862
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   source  863 non-null    object
 1   url     863 non-null    object
 2   rating  863 non-null    object
dtypes: object(3)
memory usage: 20.4+ KB

In [6]:
df.head()

,source,url,rating
0,here,http://thefangirlverdict.com/index/all-reviews...,NA
1,this post,https://thefangirlverdict.com/2021/01/12/dear-...,NA
2,1% of Anything [Something About 1%],http://thefangirlverdict.com/2017/04/29/flash-...,B+
3,18 Again,https://thefangirlverdict.com/2021/01/08/revie...,A
4,18×2 Beyond Youthful Days [Movie] [Japan-Taiwan],https://thefangirlverdict.com/2024/11/17/flash...,A-

In [7]:
# handle NAs
df = df.replace("NA", np.nan)
df.dropna(inplace=True)

In [8]:
df["year"] = df.apply(lambda row: re.search(r"\d+", row["url"]).group(), axis=1)
# df["source"] = df.apply(lambda row: unidecode(row["source"]), axis=1)
df.head()

,source,url,rating,year
2,1% of Anything [Something About 1%],http://thefangirlverdict.com/2017/04/29/flash-...,B+,2017
3,18 Again,https://thefangirlverdict.com/2021/01/08/revie...,A,2021
4,18×2 Beyond Youthful Days [Movie] [Japan-Taiwan],https://thefangirlverdict.com/2024/11/17/flash...,A-,2024
5,"1st Shop Of Coffee Prince, The [Coffee Prince]",http://thefangirlverdict.com/2019/01/03/review...,A,2019
6,20’s [Twenty Years Old],http://thefangirlverdict.com/2015/04/10/flash-...,B+,2015

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 818 entries, 2 to 862
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   source  818 non-null    object
 1   url     818 non-null    object
 2   rating  818 non-null    object
 3   year    818 non-null    object
dtypes: object(4)
memory usage: 32.0+ KB

In [10]:
df.to_csv("df.csv", encoding="utf-8", index=False)